<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>RelistenUserService-4d3c1af6-9f41-4f74-b8dd-2b6ab8eac2e2</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageReference Include="OpenIddict.AspNetCore" Version="7.6.0" />
    <PackageReference Include="OpenIddict.Client.SystemNetHttp" Version="7.6.0" />
    <PackageReference Include="OpenIddict.Client.WebIntegration" Version="7.6.0" />
    <PackageReference Include="OpenIddict.EntityFrameworkCore" Version="7.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Relisten.Accounts.Contracts\Relisten.Accounts.Contracts.csproj" />
  </ItemGroup>
</Project>
