// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RelistenUserService.Persistence;

#nullable disable

namespace RelistenUserService.Persistence.Migrations
{
    [DbContext(typeof(AccountsDbContext))]
    [Migration("20260719081752_AddFavoritesLibrary")]
    partial class AddFavoritesLibrary
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id");

                    b.ToTable("data_protection_keys", "identity");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApplicationType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("application_type");

                    b.Property<string>("ClientId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("text")
                        .HasColumnName("client_secret");

                    b.Property<string>("ClientType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("client_type");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("concurrency_token");

                    b.Property<string>("ConsentType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("consent_type");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("text")
                        .HasColumnName("display_names");

                    b.Property<string>("JsonWebKeySet")
                        .HasColumnType("text")
                        .HasColumnName("json_web_key_set");

                    b.Property<string>("Permissions")
                        .HasColumnType("text")
                        .HasColumnName("permissions");

                    b.Property<string>("PostLogoutRedirectUris")
                        .HasColumnType("text")
                        .HasColumnName("post_logout_redirect_uris");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<string>("RedirectUris")
                        .HasColumnType("text")
                        .HasColumnName("redirect_uris");

                    b.Property<string>("Requirements")
                        .HasColumnType("text")
                        .HasColumnName("requirements");

                    b.Property<string>("Settings")
                        .HasColumnType("text")
                        .HasColumnName("settings");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("openiddict_applications", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_openiddict_applications_id_uuid_v7", "uuid_extract_version(id) IS NOT DISTINCT FROM 7");
                        });
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<string>("Scopes")
                        .HasColumnType("text")
                        .HasColumnName("scopes");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("subject");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                    b.ToTable("openiddict_authorizations", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_openiddict_authorizations_id_uuid_v7", "uuid_extract_version(id) IS NOT DISTINCT FROM 7");
                        });
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreScope<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("concurrency_token");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Descriptions")
                        .HasColumnType("text")
                        .HasColumnName("descriptions");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("text")
                        .HasColumnName("display_names");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<string>("Resources")
                        .HasColumnType("text")
                        .HasColumnName("resources");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("openiddict_scopes", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_openiddict_scopes_id_uuid_v7", "uuid_extract_version(id) IS NOT DISTINCT FROM 7");
                        });
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<Guid?>("AuthorizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("authorization_id");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_date");

                    b.Property<string>("Payload")
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<DateTime?>("RedemptionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("redemption_date");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference_id");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("subject");

                    b.Property<string>("Type")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationId");

                    b.HasIndex("ReferenceId")
                        .IsUnique();

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                    b.ToTable("openiddict_tokens", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_openiddict_tokens_id_uuid_v7", "uuid_extract_version(id) IS NOT DISTINCT FROM 7");
                        });
                });

            modelBuilder.Entity("RelistenUserService.Identity.Entities.ExternalIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EmailAtProvider")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email_at_provider");

                    b.Property<bool?>("EmailIsPrivateRelay")
                        .HasColumnType("boolean")
                        .HasColumnName("email_is_private_relay");

                    b.Property<DateTimeOffset?>("EmailObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_observed_at");

                    b.Property<bool?>("EmailVerifiedAtProvider")
                        .HasColumnType("boolean")
                        .HasColumnName("email_verified_at_provider");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("issuer");

                    b.Property<DateTimeOffset>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("ProviderSubject")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("provider_subject");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Issuer", "ProviderSubject")
                        .IsUnique();

                    b.HasIndex("UserId", "Issuer")
                        .IsUnique();

                    b.ToTable("external_identities", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_external_identities_id_uuid_v7", "uuid_extract_version(id) IS NOT DISTINCT FROM 7");
                        });
                });

            modelBuilder.Entity("RelistenUserService.Identity.Entities.NativeSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AbsoluteExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("absolute_expires_at");

                    b.Property<DateTimeOffset>("AuthenticatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("authenticated_at");

                    b.Property<Guid>("AuthorizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("authorization_id");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("device_name");

                    b.Property<DateTimeOffset>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Platform")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("platform");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<int>("SecurityVersion")
                        .HasColumnType("integer")
                        .HasColumnName("security_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationId")
                        .IsUnique();

                    b.HasIndex("UserId", "RevokedAt", "AbsoluteExpiresAt");

                    b.ToTable("native_sessions", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_native_sessions_id_uuid_v7", "uuid_extract_version(id) IS NOT DISTINCT FROM 7");
                        });
                });

            modelBuilder.Entity("RelistenUserService.Identity.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<long>("LifecycleGeneration")
                        .HasColumnType("bigint")
                        .HasColumnName("lifecycle_generation");

                    b.Property<int>("SecurityVersion")
                        .HasColumnType("integer")
                        .HasColumnName("security_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("username");

                    b.Property<DateTimeOffset?>("UsernameChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("username_changed_at");

                    b.Property<DateTimeOffset?>("UsernameReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("username_reviewed_at");

                    b.Property<long>("UsernameVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("username_version");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.HasIndex("Status", "UpdatedAt");

                    b.ToTable("users", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_users_id_uuid_v7", "uuid_extract_version(id) IS NOT DISTINCT FROM 7");

                            t.HasCheckConstraint("ck_users_status", "status IN ('active', 'disabled', 'deleting')");

                            t.HasCheckConstraint("ck_users_username", "username = lower(username) AND username ~ '^[a-z0-9_]{3,30}$'");
                        });
                });

            modelBuilder.Entity("RelistenUserService.Identity.Entities.UsernameCommandReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("ExpectedUsernameVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("expected_username_version");

                    b.Property<byte[]>("PayloadHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("payload_hash");

                    b.Property<string>("StoredResult")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("stored_result");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("username_command_receipts", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_username_command_receipts_id_uuid_v7", "uuid_extract_version(id) IS NOT DISTINCT FROM 7");
                        });
                });

            modelBuilder.Entity("RelistenUserService.Identity.Entities.UsernameHold", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ReleaseAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("release_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseAt");

                    b.HasIndex("UserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("username_holds", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_username_holds_id_uuid_v7", "uuid_extract_version(id) IS NOT DISTINCT FROM 7");
                        });
                });

            modelBuilder.Entity("RelistenUserService.Library.Entities.Favorite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CatalogType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("catalog_type");

                    b.Property<Guid>("CatalogUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("catalog_uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CatalogType", "CatalogUuid")
                        .IsUnique();

                    b.ToTable("favorites", "user_data", t =>
                        {
                            t.HasCheckConstraint("ck_favorites_catalog_type", "catalog_type IN ('artist', 'show', 'source', 'source_track', 'song', 'tour', 'venue')");

                            t.HasCheckConstraint("ck_favorites_id_uuid_v7", "uuid_extract_version(id) IS NOT DISTINCT FROM 7");
                        });
                });

            modelBuilder.Entity("RelistenUserService.Library.Entities.FavoriteMutationReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CanonicalFavoriteId")
                        .HasColumnType("uuid")
                        .HasColumnName("canonical_favorite_id");

                    b.Property<string>("CatalogType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("catalog_type");

                    b.Property<Guid>("CatalogUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("catalog_uuid");

                    b.Property<bool>("Changed")
                        .HasColumnType("boolean")
                        .HasColumnName("changed");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DesiredState")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("desired_state");

                    b.Property<long>("LibraryRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("library_revision");

                    b.Property<byte[]>("PayloadHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("payload_hash");

                    b.Property<Guid?>("SubmittedFavoriteId")
                        .HasColumnType("uuid")
                        .HasColumnName("submitted_favorite_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("SubmittedFavoriteId");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("favorite_mutation_receipts", "user_data", t =>
                        {
                            t.HasCheckConstraint("ck_favorite_mutation_receipts_canonical_favorite_id", "canonical_favorite_id IS NULL OR uuid_extract_version(canonical_favorite_id) = 7");

                            t.HasCheckConstraint("ck_favorite_mutation_receipts_catalog_type", "catalog_type IN ('artist', 'show', 'source', 'source_track', 'song', 'tour', 'venue')");

                            t.HasCheckConstraint("ck_favorite_mutation_receipts_desired_state", "desired_state IN ('favorite', 'not_favorite')");

                            t.HasCheckConstraint("ck_favorite_mutation_receipts_id_uuid_v7", "uuid_extract_version(id) IS NOT DISTINCT FROM 7");

                            t.HasCheckConstraint("ck_favorite_mutation_receipts_payload", "octet_length(payload_hash) = 32 AND ((desired_state = 'favorite' AND submitted_favorite_id IS NOT NULL) OR (desired_state = 'not_favorite' AND submitted_favorite_id IS NULL)) AND (desired_state <> 'favorite' OR canonical_favorite_id IS NOT NULL) AND library_revision >= 0");

                            t.HasCheckConstraint("ck_favorite_mutation_receipts_submitted_favorite_id", "submitted_favorite_id IS NULL OR uuid_extract_version(submitted_favorite_id) = 7");
                        });
                });

            modelBuilder.Entity("RelistenUserService.Library.Entities.LibraryChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CatalogType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("catalog_type");

                    b.Property<Guid>("CatalogUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("catalog_uuid");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("change_type");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<Guid>("FavoriteId")
                        .HasColumnType("uuid")
                        .HasColumnName("favorite_id");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("FavoriteId");

                    b.HasIndex("UserId", "ChangedAt");

                    b.HasIndex("UserId", "Revision")
                        .IsUnique();

                    b.ToTable("library_changes", "user_data", t =>
                        {
                            t.HasCheckConstraint("ck_library_changes_catalog_type", "catalog_type IN ('artist', 'show', 'source', 'source_track', 'song', 'tour', 'venue')");

                            t.HasCheckConstraint("ck_library_changes_change_type", "change_type IN ('favorite_added', 'favorite_removed')");

                            t.HasCheckConstraint("ck_library_changes_favorite_id_uuid_v7", "uuid_extract_version(favorite_id) IS NOT DISTINCT FROM 7");

                            t.HasCheckConstraint("ck_library_changes_id_uuid_v7", "uuid_extract_version(id) IS NOT DISTINCT FROM 7");

                            t.HasCheckConstraint("ck_library_changes_revision", "revision > 0");
                        });
                });

            modelBuilder.Entity("RelistenUserService.Library.Entities.LibraryState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("library_states", "user_data", t =>
                        {
                            t.HasCheckConstraint("ck_library_states_id_uuid_v7", "uuid_extract_version(id) IS NOT DISTINCT FROM 7");

                            t.HasCheckConstraint("ck_library_states_revision", "revision >= 0");
                        });
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization<System.Guid>", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication<System.Guid>", "Application")
                        .WithMany("Authorizations")
                        .HasForeignKey("ApplicationId");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken<System.Guid>", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication<System.Guid>", "Application")
                        .WithMany("Tokens")
                        .HasForeignKey("ApplicationId");

                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization<System.Guid>", "Authorization")
                        .WithMany("Tokens")
                        .HasForeignKey("AuthorizationId");

                    b.Navigation("Application");

                    b.Navigation("Authorization");
                });

            modelBuilder.Entity("RelistenUserService.Identity.Entities.ExternalIdentity", b =>
                {
                    b.HasOne("RelistenUserService.Identity.Entities.User", "User")
                        .WithMany("ExternalIdentities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RelistenUserService.Identity.Entities.NativeSession", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization<System.Guid>", null)
                        .WithOne()
                        .HasForeignKey("RelistenUserService.Identity.Entities.NativeSession", "AuthorizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RelistenUserService.Identity.Entities.User", "User")
                        .WithMany("NativeSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RelistenUserService.Identity.Entities.UsernameCommandReceipt", b =>
                {
                    b.HasOne("RelistenUserService.Identity.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RelistenUserService.Identity.Entities.UsernameHold", b =>
                {
                    b.HasOne("RelistenUserService.Identity.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RelistenUserService.Library.Entities.Favorite", b =>
                {
                    b.HasOne("RelistenUserService.Identity.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RelistenUserService.Library.Entities.FavoriteMutationReceipt", b =>
                {
                    b.HasOne("RelistenUserService.Identity.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RelistenUserService.Library.Entities.LibraryChange", b =>
                {
                    b.HasOne("RelistenUserService.Identity.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RelistenUserService.Library.Entities.LibraryState", b =>
                {
                    b.HasOne("RelistenUserService.Identity.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication<System.Guid>", b =>
                {
                    b.Navigation("Authorizations");

                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization<System.Guid>", b =>
                {
                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("RelistenUserService.Identity.Entities.User", b =>
                {
                    b.Navigation("ExternalIdentities");

                    b.Navigation("NativeSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
